name: terraform-ci

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"

  push:
    branches:
      - main
      - test-ci
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"

  workflow_dispatch:
      

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform fmt/validate/plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform

    env:
      AWS_REGION: ap-south-1
      AWS_ROLE_TO_ASSUME: ${{ vars.AWS_ROLE_ARN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend for CI)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

      # âœ… Plan runs ONLY after you add OIDC role secret (AWS_ROLE_TO_ASSUME)
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::969318514380:role/GitHubActions-Terraform-Role
            aws-region: ap-south-1


      - name: Terraform init (real backend)
        run: terraform init

      - name: Terraform plan (PR only)
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color

      - name: Terraform apply (manual only)
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
